version: '3.8'
services:

  datadog:
    image: datadog/agent:latest #gcr.io/datadoghq/agent:latest
    container_name: datadog
    restart: unless-stopped
    environment:
      - DOCKER_CONTENT_TRUST=1
      - DD_SITE=datadoghq.eu
      - DD_API_KEY=${DD_API_KEY}
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=1
      #- DD_DOGSTATSD_PORT=<NEW_DOGSTATSD_PORT>
      - DD_DOCKER_LABELS_AS_TAGS={"my.custom.label.project":"globalid","my.custom.label.version":"1.0"}
      - DD_TAGS="tool:artillery mode:load scenario:system env:local"
    volumes:
      - ./conf.yaml:/conf.d/conf.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    ports:
      - "8126:8125/udp"
