config:
  target: "http://json_server:3000"
  phases:
    - duration: 1
      arrivalCount: 1
      name: "Debug Stage"
  environments:
    local:
      target: "http://localhost:3001"
      phases:
        - duration: 1
          arrivalCount: 1
          name: "Debug Stage"
    remote:
      target: "{{ $processEnvironment.BASE_URL }}"
      phases:
        - duration: 1
          arrivalCount: 1
          name: "Debug Stage"
  ensure:
    thresholds:
      - "vusers.failed": 1
    maxErrorRate: 1
  http:
    timeout: 20
    extendedMetrics: true
  processor: "../processors/main.js"
  variables:
    commentsNumber: 2
  payload:
    path: "./../data/people.csv"
    fields:
      - "userId"
      - "userName"
      - "userEmail"
    order: sequence # sequence # random
    skipHeader: true
  defaults:
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
  plugins:
    ensure: { }
    ensure-shutdown: { }
    expect:
      outputFormat: pretty # prettyError # pretty # silent
    metrics-by-endpoint:
      useOnlyRequestNames: true
    publish-metrics:
      - type: datadog
        host: "{{ $processEnvironment.STATSD_SERVER_ADDRESS }}" # "127.0.0.1"
        port: "{{ $processEnvironment.STATSD_SERVER_PORT }}" # 8125 # port to datadog agent
        prefix: 'artillery.publish_metrics_plugin.'
        tags:
          - 'tool:artillery'
          - 'mode:{{ $processEnvironment.CONFIG }}' #'mode:load'
          - 'scenario:{{ $processEnvironment.SCENARIO_NAME }}' #'scenario:system'
          - 'env:{{ $environment }}' # 'env:local'
        event:
          priority: low
          tags:
            - "testId:mytest123"
    #statsd: # https://github.com/artilleryio/artillery-plugin-statsd
    #  host: "{{ $processEnvironment.STATSD_SERVER_ADDRESS }}" # localhost
    #  port: "{{ $processEnvironment.STATSD_SERVER_PORT }}" # 8125 or 8126 for datadog
    #  # Prefix Format: "artillery.<SCENARIO_NAME>.<CONFIG_NAME>"
    #  # Set: "artillery.statsd_plugin" when publishing metrics to Datadog (using agent)
    #  prefix: "artillery.statsd_plugin"
    advanced-metrics:
      host: "{{ $processEnvironment.STATSD_SERVER_ADDRESS }}" # statsd server host
      port: "{{ $processEnvironment.STATSD_SERVER_PORT }}" # statsd port
      prefix: "artillery.publish_metrics_plugin" # metrics prefix. Metrics path will be: {prefix}.plugins.advanced_metrics.errors

