config:
  target: "http://json_server:3000"
  phases:
    - duration: 120
      arrivalCount: 60
      name: "My Load Stage"
  environments:
    local:
      target: "http://json_server:3000"
      phases:
        - duration: 120
          arrivalRate: 3
          maxVusers: 5
#        - duration: 120
#          arrivalRate: 8
#          maxVusers: 10
#        - duration: 180
#          arrivalRate: 12
#          maxVusers: 15
    remote:
      target: "{{ $processEnvironment.BASE_URL }}"
      phases:
        - duration: 120
          arrivalRate: 5
          maxVusers: 5
        - duration: 120
          arrivalRate: 8
          maxVusers: 10
        - duration: 180
          arrivalRate: 12
          maxVusers: 15
  ensure:
    thresholds:
      - "http.response_time.p99": 15000
      - "http.response_time.p95": 14000
    conditions:
      - expression: vusers.failed == 0
        strict: true
        shutdown: true
    #maxErrorRate: 1
  http:
    timeout: 20
    extendedMetrics: false
  processor: "../processors/main.js"
  variables:
    commentsNumber: 2
  payload:
    path: "./../data/people.csv"
    fields:
      - "userId"
      - "userName"
      - "userEmail"
    order: sequence # sequence # random
    skipHeader: true
  defaults:
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
  plugins:
    ensure: {}
    ensure-shutdown: {}
    expect:
      outputFormat: pretty # prettyError # pretty # silent
    metrics-by-endpoint:
      useOnlyRequestNames: true
    publish-metrics:
      - type: datadog
        host: "{{ $processEnvironment.STATSD_SERVER_ADDRESS }}" # "127.0.0.1"
        port: "{{ $processEnvironment.STATSD_SERVER_PORT }}" # 8125 # port to datadog agent
        prefix: 'artillery.publish_metrics_plugin.'
        tags:
          - 'tool:artillery'
          - 'mode:{{ $processEnvironment.CONFIG }}' #'mode:load'
          - 'scenario:{{ $processEnvironment.SCENARIO_NAME }}' #'scenario:system'
          - 'env:{{ $environment }}' # 'env:local'
        event:
          priority: low
          tags:
            - "testId:mytest123"
    advanced-metrics:
      host: "{{ $processEnvironment.STATSD_SERVER_ADDRESS }}" # statsd server host
      port: "{{ $processEnvironment.STATSD_SERVER_PORT }}" # statsd port
      prefix: "artillery.publish_metrics_plugin" # metrics prefix. Metrics path will be: {prefix}.plugins.advanced_metrics.errors

